// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfmQ9YjSET262-2e8RDSS_JMZyQ_v69zM',
    appId: '1:368594614699:web:e5b22ce8af7e9384a3baee',
    messagingSenderId: '368594614699',
    projectId: 'fir-example-95e90',
    authDomain: 'fir-example-95e90.firebaseapp.com',
    storageBucket: 'fir-example-95e90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-vn8GtyDnmhGUwmC8m8VxoVYYyEtV548',
    appId: '1:368594614699:android:cb5c7eb61ca7eceba3baee',
    messagingSenderId: '368594614699',
    projectId: 'fir-example-95e90',
    storageBucket: 'fir-example-95e90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQa3AZrkwo95sSq1s0kOWm48f3G0gRpsc',
    appId: '1:368594614699:ios:66c1debee736ecf7a3baee',
    messagingSenderId: '368594614699',
    projectId: 'fir-example-95e90',
    storageBucket: 'fir-example-95e90.appspot.com',
    iosBundleId: 'com.example.firebaseexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQa3AZrkwo95sSq1s0kOWm48f3G0gRpsc',
    appId: '1:368594614699:ios:98ea5c85193d6905a3baee',
    messagingSenderId: '368594614699',
    projectId: 'fir-example-95e90',
    storageBucket: 'fir-example-95e90.appspot.com',
    iosBundleId: 'com.example.firebaseexample.RunnerTests',
  );
}
